// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pi.FileTransfer.Infrastructure;

#nullable disable

namespace Pi.FileTransfer.Infrastructure.Migrations
{
    [DbContext(typeof(FileContext))]
    [Migration("20230210101958_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Pi.FileTransfer.Infrastructure.DbModels.Destination", b =>
                {
                    b.Property<string>("Folder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Folder");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Pi.FileTransfer.Infrastructure.DbModels.File", b =>
                {
                    b.Property<string>("Folder")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Folder");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
